#!/usr/bin/env bash

REPO="phil";

STAMP=`date "+%y%m%d-%H%M%S"`
MYDIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

NODEVER="8"
NODEDIR="$MYDIR/node";
BINDIR="$MYDIR/bin";
WIN64="$BINDIR/win64"
WIN32="$BINDIR/win32"
LINUX="$BINDIR/linux"
DARWIN="$BINDIR/darwin"

PKG=/usr/bin/pkg;
OPT=$1;

cd $MYDIR;

function _inc {
  cd $NODEDIR;
  /usr/share/scripts/bash/git-inc-version  
  cd $MYDIR;
}

function _sync {
  echo "syncing $NODEDIR > $BINDIR";
  rsync -ra $NODEDIR/data $BINDIR/files;
  rsync -ra $NODEDIR/config.json $BINDIR/files;
  rsync -ra $NODEDIR/prpt $BINDIR/files;
}

function _win64 {
  rsync -ra $BINDIR/files/* $WIN64;
  rsync -ra $NODEDIR/node_modules/bsfw/binlib/win64/* $WIN64;
  echo "Compiling $WIN64 .."

  
  ## SERVER
  $PKG $NODEDIR/package.json -t node$NODEVER-win -o $WIN64/$REPO-server;

  ## CLIENT
  # $PKG -c $NODEDIR/$REPO.package.json $NODEDIR/$REPO.js -t node$NODEVER-win -o $WIN64/$REPO;

}

function _linux {
  rsync -ra $BINDIR/files/* $LINUX;
  rsync -ra $NODEDIR/node_modules/bsfw/binlib/linux/* $LINUX;
  echo "Compiling $LINUX .."
  
  ## SERVER
  $PKG $NODEDIR/package.json -t node$NODEVER-linux -o $LINUX/$REPO-server;
  
  ## CLIENT
  # $PKG -c $NODEDIR/$REPO.package.json $NODEDIR/$REPO.js -t node$NODEVER-linux -o $LINUX/$REPO;
}

_inc;
_sync;
_win64;
_linux;
